#####################################################################
print ("先确认filted文件夹中有相应的文件，可修改文件名，勿改内容。")
print ("按照提示输入文件名，注意包含正确的扩展名，如xx.wjc。")
print ("输入后回车可进行下一次输入，如想结束输入q后回车。")
print ('*'*66)
filex=''
filted_set=[]
while filex!='q':
       filex=input("请输入文件名或者输入q结束输入：")
       if filex=='q':
              pass
       elif filex[-4:]=='.wjc':
              filted_set.append(filex)
       else:
              print ("输入正确的扩展名！")
#print (filted_set)
print ("共输入 %d 个文件" %len(filted_set))
#####################################################################

up_path=r'/PromicsWJC/'
path=up_path+'filted/'


def read(filtedx):
#读文件，包含标题，在最后加来源
    filex=open(path+filtedx)
    filted_data=[]
    linex=1
    while linex:
        linex=filex.readline()
        if len(linex)>1:
            linex=linex[:-1]+'from '+filtedx[:-4]
            filted_data.append(linex.split('\t'))
    filex.close()
    return filted_data

seq_set=[]
for filtedxx in filted_set:
    seq_set.append(read(filtedxx))

#####################################################################
#seq转为dic，获取ID的并集
dic_set=[]
IDset=[]
for seq in seq_set:
    dic={}
    for line in seq[1:]:
        dic[line[0]]=line[1:]
        if line[0] not in IDset:
            IDset.append(line[0])
    dic_set.append(dic)
#print (len(IDset))
#print (IDset)
#####################################################################

#####################################################################
#获取ID的交集
dickey_set=[]
for dicx in dic_set:
    dicxkey=[]
    for keyx in dicx:
        dicxkey.append(keyx)
    dickey_set.append(dicxkey)

newIDset=IDset[:]
for ID in IDset:
    for dickeyx in dickey_set:
        if ID not in dickeyx:
            if ID in newIDset:
                newIDset.remove(ID)
#print (len(newIDset))
#####################################################################


seq_final=[]
final_line0=['Majority protein IDs']
for seq in seq_set:
    final_line0=final_line0+seq[0][1:-1]
    final_line0.append('from **')
seq_final.append(final_line0)


for ID in newIDset:
    IDline=[ID]
    #print (IDline)
    for dic in dic_set:
        IDline.append(dic[ID])
    
    seq_final.append(IDline)

#***
name_list=''
for filex in filted_set:
    name_list=name_list+filex[:-4]+'_'
name_list=name_list[:-1]

out_path=up_path+'compared/'+name_list+'.xls'
output=open(out_path,'w')
output.write('Generated by Jichao. Do check the data mannually!\n')
output.close()

#####################################################################
#写入文件
add=open(out_path,'a')
for i in seq_final[0]:
    add.write(str(i)+'\t')
add.write('\n')
for line in seq_final[1:]:
    add.write(str(line[0]))
    add.write('\t')
    for data in line[1:]:
        for word in data:
            add.write(str(word)+'\t')
    add.write('\n')
add.close()
#####################################################################

print ('*'*66)
print ("数据比对完成，结果在compared目录下。")
print ("文件名为所比较数据文件名用下划线连接，请核对。")

print ("如果本程序给您提供便利，帮我装几盒枪头呗~~~")
print ('$'*66)
input("按任意键退出")
